server.port=8080

# H2 Console - DEBE estar así
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Base de datos
spring.datasource.url=jdbc:h2:mem:taskmaster
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true